# environments:
#   staging:
#     values:
#       - values-dev.yaml
#   production:
#     values:
#       - values-prod.yaml

releases:
  - name: kafka
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    version: 32.1.3
    namespace: dev
    values: 
      - values-dev.yaml

  - name: kafka
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    version: 32.1.3
    namespace: prod
    values: 
      - values-prod.yaml