apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: homework 
---
apiVersion: v1
kind: Secret
metadata:
  name: cd-token
  namespace: homework
  annotations:
    kubernetes.io/service-account.name: cd
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hw-cd-admin
  namespace: homework
subjects:
- kind: ServiceAccount
  name: cd
  namespace: homework
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io