apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: homework
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: monitoring-sa
      # nodeSelector:
      #   homework: "true"
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8000
            initialDelaySeconds: 0
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: [ "rm", "-f", "/homework/index.html" ]
          volumeMounts:
            - name: hw-pvc
              mountPath: "/homework"
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
            - name: hw-configmap
              mountPath: /homework/conf
      initContainers:
        - name: download-static
          image: busybox:1.28
          command: ['wget', '-O', '/init/index.html', 'http://info.cern.ch']
          volumeMounts:
            - name: hw-pvc
              mountPath: "/init"
        - name: get-metrics
          image: nginx:latest
          command: 
            - sh
            - -c
            - |
              APISERVER=https://kubernetes.default.svc
              SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
              NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
              TOKEN=$(cat ${SERVICEACCOUNT}/token)
              CACERT=${SERVICEACCOUNT}/ca.crt
              curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET "${APISERVER}/metrics" -o /init/metrics.html || echo "failed" > /init/metrics.html

          volumeMounts:
            - name: hw-pvc
              mountPath: "/init"
      volumes:
        - name: hw-pvc
          persistentVolumeClaim:
              claimName: hw-pvc
        - name: hw-configmap
          configMap:
            name: hw-configmap
        - name: nginx-conf 
          configMap:
            name: nginx-conf
            items:
            - key: default.conf
              path: default.conf

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: homework
data:
  default.conf: |
    server {
        listen 8000;
        server_name homework.otus;
        location / { 
        root /homework;
        index index.html;
        }
    }
    
