apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-sa
  namespace: homework 
# automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-sa-token
  namespace: homework
  annotations:
    kubernetes.io/service-account.name: monitoring-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-cluster-role
rules:
- nonResourceURLs: ["/metrics"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-monitoring
  namespace: homework
subjects:
- kind: ServiceAccount
  name: monitoring-sa
roleRef:
  kind: ClusterRole
  name: monitoring-cluster-role
  apiGroup: rbac.authorization.k8s.io