apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: {{ .Values.namespace }}
data:
  default.conf: |
    server {
        listen 8000;

        server_name _;
        root /homework;
        index index.html;
        location / { 
          try_files $uri $uri/ /index.html;
        }
    }
    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hw-configmap
  namespace: homework
data:
  key1: value1
  key2: value2
  test: test1
  