apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Values.namespace }} 
# automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceAccount }}-token
  namespace: {{ .Values.namespace }} 
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-cluster-role
rules:
- nonResourceURLs: ["/metrics"]
  verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-monitoring
  namespace: {{ .Values.namespace }} 
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Values.namespace }} 
roleRef:
  kind: ClusterRole
  name: monitoring-cluster-role
  apiGroup: rbac.authorization.k8s.io