apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hw-pvc
  namespace: homework
spec:
  storageClassName: "hw" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---