apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hw-pvc
  namespace: homework
spec:
  storageClassName: "hw" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: hw-pvc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---